language: ruby
rvm:
 - 2.0.0
bundler_args: "--without development"
before_install:
  - gem install bundler --pre
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script: true
matrix:
  allow_failures:
    - rvm: 2.0.0
