language: ruby
rvm:
 - 2.2.0
bundler_args: "--without development"
before_install:
  - gem install bundler --pre
before_script:
  - createuser -s beerclub
  - createdb beerclub_test -U beerclub 
  - RAILS_ENV=test bundle exec rake db:create db:schema:load db:test:prepare
script:
  - bundle exec rspec spec
matrix:
  allow_failures:
    - rvm: 2.2.0
