common: &COMMON
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: beerclub

production:
  <<: *COMMON

development:
  <<: *COMMON
  database: beerclub_development

test:
  <<: *COMMON
  database: beerclub_test
  username: postgres
