mysql: &MYSQL
  adapter: mysql2
  encoding: utf8

postgres: &POSTGRES
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: beerclub

production:
  <<: *MYSQL

development:
  <<: *POSTGRES
  database: beerclub_development

test:
  <<: *POSTGRES
  database: beerclub_test
